from datetime import datetime
from zoneinfo import ZoneInfo

from app.core.config import APP_TIMEZONE
from app.services.event_formatting import build_schedule_metadata, ensure_professional_title
from app.services.google_auth_service import build_google_event_payload


LOCAL = ZoneInfo(APP_TIMEZONE)


def test_ensure_professional_title_removes_time_words():
    title = ensure_professional_title("schedule meeting with kalpesh tomorrow at 5pm for 2 hours")
    assert title == "Meeting with Kalpesh"


def test_ensure_professional_title_normalizes_common_informal_titles():
    assert ensure_professional_title("team") == "Team Collaboration Meeting"
    assert ensure_professional_title("with kalpesh ghodekar") == "Meeting with Kalpesh Ghodekar"
    assert ensure_professional_title("meeting tomorrow") == "Project Discussion Meeting"
    assert ensure_professional_title("client call") == "Client Strategy Call"
    assert ensure_professional_title("now a with Rahul Dada") == "Meeting with Rahul Dada"
    assert ensure_professional_title("pm testing with tester to 5 00 pm") == "Project Testing Session"


def test_build_schedule_metadata_formats_title_and_attendees():
    dt = datetime(2026, 5, 25, 17, 0, tzinfo=LOCAL)
    metadata = build_schedule_metadata(
        original_prompt="project discussion with rahul",
        parsed_datetime=dt,
        duration_minutes=60,
    )
    assert metadata.title == "Project Discussion with Rahul"
    assert metadata.attendees == ["Rahul"]
    assert metadata.timezone == APP_TIMEZONE
    assert "Meeting Type:" in metadata.description
    assert "Generated By:" in metadata.description
    assert "Yashraj AI Assistant OS" in metadata.description


def test_build_schedule_metadata_classifies_event_type_and_priority():
    dt = datetime(2026, 5, 25, 11, 0, tzinfo=LOCAL)
    metadata = build_schedule_metadata(
        original_prompt="urgent interview with tcs asap",
        parsed_datetime=dt,
        duration_minutes=45,
    )
    assert metadata.event_type == "urgent"
    assert metadata.priority == "high"
    assert metadata.color_id == "11"
    assert metadata.duplicate_risk == "medium"
    assert "Agenda:" in metadata.description
    assert "Timezone:" in metadata.description


def test_build_schedule_metadata_classifies_common_event_types():
    dt = datetime(2026, 5, 25, 11, 0, tzinfo=LOCAL)
    interview = build_schedule_metadata("interview with tcs", dt, 60)
    client = build_schedule_metadata("client meeting infosys", dt, 60)
    standup = build_schedule_metadata("daily standup", dt, 15)
    academic = build_schedule_metadata("college presentation", dt, 30)

    assert interview.title == "TCS Interview Session"
    assert interview.event_type == "interview"
    assert interview.color_id == "9"
    assert client.title == "Client Meeting - Infosys"
    assert client.event_type == "client"
    assert client.color_id == "10"
    assert standup.title == "Standup"
    assert standup.event_type == "standup"
    assert standup.color_id == "8"
    assert academic.title == "Academic Presentation"
    assert academic.event_type == "academic"
    assert academic.color_id == "3"


def test_build_google_event_payload_includes_description_and_color():
    start = datetime(2026, 5, 25, 17, 0, tzinfo=LOCAL)
    end = datetime(2026, 5, 25, 18, 0, tzinfo=LOCAL)
    payload = build_google_event_payload(
        "Client Call - Infosys",
        start,
        end,
        description="Structured description",
        color_id="11",
    )
    assert payload["summary"] == "Client Call - Infosys"
    assert payload["description"] == "Structured description"
    assert payload["colorId"] == "11"
    assert payload["start"]["timeZone"] == APP_TIMEZONE
    assert payload["end"]["timeZone"] == APP_TIMEZONE


def test_build_google_event_payload_filters_non_email_attendees():
    start = datetime(2026, 5, 25, 17, 0, tzinfo=LOCAL)
    end = datetime(2026, 5, 25, 18, 0, tzinfo=LOCAL)
    payload = build_google_event_payload(
        "Meeting with Kalpesh Ghodekar",
        start,
        end,
        attendees=["Kalpesh Ghodekar", "kalpesh@example.com"],
    )
    assert payload["attendees"] == [{"email": "kalpesh@example.com"}]
