import asyncio
from datetime import datetime
from types import SimpleNamespace

import pytest

from app.core.config import APP_TIMEZONE
from app.schemas.calendar_schema import CalendarCreateRequest
from app.services.calendar_service import _ensure_timezone, create_event, sync_google_event_for_retry


class DummySession:
    def __init__(self):
        self.added = None

    def add(self, event):
        self.added = event

    async def commit(self):
        return None

    async def refresh(self, event):
        return None

    async def execute(self, statement):
        return SimpleNamespace(scalar_one_or_none=lambda: None)


class RetrySession:
    def __init__(self, event):
        self.event = event

    async def execute(self, statement):
        return SimpleNamespace(scalar_one_or_none=lambda: self.event)

    async def commit(self):
        return None

    async def refresh(self, event):
        return None


def _run_async(coro):
    return asyncio.run(coro)


def test_ensure_timezone_normalizes_naive_values():
    value = datetime(2026, 5, 25, 10, 0)
    normalized = _ensure_timezone(value)
    assert normalized.tzinfo is not None
    assert str(normalized.tzinfo) == APP_TIMEZONE


def test_create_event_rejects_duplicate_overlap(monkeypatch):
    async def fake_find_conflict(db, user_id, new_start, new_end):
        return SimpleNamespace(id=44)

    monkeypatch.setattr("app.services.calendar_service._find_conflict", fake_find_conflict)

    db = DummySession()
    payload = CalendarCreateRequest(
        title="Team Sync Meeting",
        start_time=datetime(2026, 5, 25, 10, 0),
        end_time=datetime(2026, 5, 25, 11, 0),
    )

    with pytest.raises(ValueError, match="Event conflict detected"):
        _run_async(create_event(db, 1, payload))


def test_create_event_formats_manual_input(monkeypatch):
    async def fake_find_conflict(db, user_id, new_start, new_end):
        return None

    monkeypatch.setattr("app.services.calendar_service._find_conflict", fake_find_conflict)

    db = DummySession()
    payload = CalendarCreateRequest(
        title="meeting with aman tomorrow",
        description="manual notes",
        start_time=datetime(2026, 5, 25, 10, 0),
        end_time=datetime(2026, 5, 25, 11, 0),
    )

    event = _run_async(create_event(db, 1, payload))

    assert event.title == "Meeting with Aman"
    assert getattr(event, "_schedule_metadata").title == "Meeting with Aman"
    assert "Manual Notes:" in getattr(event, "_schedule_metadata").description


def test_retry_sync_preserves_normalized_title(monkeypatch):
    async def fake_credentials():
        return object()

    captured = {}

    async def fake_create_google_calendar_event(
        title,
        start_time,
        end_time,
        description=None,
        color_id=None,
        attendees=None,
        create_meet_link=True,
        reminders=None,
    ):
        captured["title"] = title
        captured["description"] = description
        captured["color_id"] = color_id
        captured["attendees"] = attendees
        captured["reminders"] = reminders
        return {"id": "google-123"}

    event = SimpleNamespace(
        id=9,
        user_id=1,
        title="Client Call - Infosys",
        start_time=datetime(2026, 5, 25, 15, 0, tzinfo=None),
        end_time=datetime(2026, 5, 25, 16, 0, tzinfo=None),
        google_event_id=None,
        sync_status="pending",
        sync_error=None,
        created_at=datetime(2026, 5, 25, 9, 0, tzinfo=None),
    )

    db = RetrySession(event)
    monkeypatch.setattr("app.services.calendar_service.load_saved_credentials", fake_credentials)
    monkeypatch.setattr("app.services.calendar_service.create_google_calendar_event", fake_create_google_calendar_event)

    synced = _run_async(sync_google_event_for_retry(db, event.id))

    assert synced.sync_status == "synced"
    assert captured["title"] == "Client Call - Infosys"
    assert "Meeting Type:" in captured["description"]
    assert "Attendees:" in captured["description"]
    assert "Generated By:" in captured["description"]
    assert captured["color_id"] == "10"


def test_create_event_rejects_duplicate_same_title_overlap(monkeypatch):
    async def fake_find_conflict(db, user_id, new_start, new_end):
        return None

    async def fake_find_duplicate(db, user_id, normalized_title, new_start, new_end):
        return SimpleNamespace(id=55)

    monkeypatch.setattr("app.services.calendar_service._find_conflict", fake_find_conflict)
    monkeypatch.setattr("app.services.calendar_service._find_duplicate_event", fake_find_duplicate)

    db = DummySession()
    payload = CalendarCreateRequest(
        title="client meeting infosys",
        start_time=datetime(2026, 5, 25, 10, 0),
        end_time=datetime(2026, 5, 25, 11, 0),
    )

    with pytest.raises(ValueError, match="Duplicate event detected"):
        _run_async(create_event(db, 1, payload))
